language: node_js
matrix:
  include:
    - node_js: '8'
      env: TEST=true
    - node_js: '10'
      env: TEST=true
    - node_js: '12'
      env: LINT=true COVERAGE=true TEST=true
before_install:
  - npm install -g npm
  - npm --version
script:
  - 'if [ -n "${LINT-}" ]; then npm run -s lint ; fi'
  - 'if [ -n "${COVERAGE-}" ]; then npm run -s coverage ; fi'
  - 'if [ -n "${TEST-}" ]; then npm run -s tests-only ; fi'
